

   
name: PR Tag Release
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  tag-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        label: ${{ github.event.pull_request.labels.*.name }}

    steps:
      - if: startsWith(matrix.label, 'release:')
        name: Testing Labels
        run: |
          release_type=`echo ${{matrix.label}} | awk -F':' '{print $NF}'`
          echo "RELEASE_TYPE=${release_type}" >> $GITHUB_ENV
          echo "Releasing: ${release_type}"
          
      - if: startsWith(matrix.label, 'release:')
        name: Checkout Code
        uses: actions/checkout@v2.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - if: startsWith(matrix.label, 'release:')
        name: Setup Github
        run: |
          git config --global user.email "macnev2013@gmail.com"
          git config --global user.name "macnev2013"

      - if: startsWith(matrix.label, 'release:')
        name: Build and Release
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          
      - if: startsWith(matrix.label, 'release:')
        name: NPM Install and Publish
        run: npm install && lerna publish ${{ env.RELEASE_TYPE }} --conventional-commits --force-publish --no-verify-access -y
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Echo Always
        run : |
         echo "Always?"
        if: always() && startsWith(matrix.label, 'release:')
